on:
  workflow_call:
    inputs:
      terraform_version:
        description: "The version of Terraform to use"
        required: true

jobs:
  terraform-test:
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
